{% set name = "emmet-core" %}
{% set version = "0.85.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 21ff6d8970a15b88010a51e2328b863dc91e1c1a4516eff138c1adc34b4faf35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - blake3
    - pymatgen-io-validation >=0.1.1
    - monty >=2024.2.2
    - pybtex >=0.24,<1.dev0
    - pydantic >=2.0
    - pydantic-settings >=2.0
    - pydantic-core >=2.0
    - pymatgen >=2024.6.10
    - python >={{ python_min }}
    - typing_extensions >=3.7

test:
  imports:
    - emmet.core
    - emmet.core.feff
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/emmet
  summary: Core Emmet Library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
