schema_version: 1

context:
  name: emmet-core
  version: 0.87.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 89bec08257f015bb5c2d463b9e5c2fe75d432e986162a41ac6a299e09f95e310

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - pip
  run:
    - inflect
    - pubchempy
    - blake3
    - pymatgen-io-validation >=0.1.1
    - monty >=2024.2.2
    - pybtex >=0.24,<1.dev0
    - pydantic >=2.12
    - pydantic-settings >=2.0
    - pymatgen
    - python >=${{ python_min }}
    - typing_extensions >=3.7
    - pymatgen-core >=2026.7.31
tests:
  - python:
      imports:
        - emmet.core
        - emmet.core.feff
      pip_check: true
      python_version:
        - ${{ python_min }}
        - '*'

about:
  summary: Core Emmet Library
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/materialsproject/emmet

extra:
  recipe-maintainers:
    - jan-janssen
